//! Guest NIC configuration for gvproxy virtio-net.
//!
//! Static addressing matches `bux_gvproxy::constants`:
//! - eth0: `192.168.127.2/24`
//! - gateway / DNS: `192.168.127.1`
//!
//! Uses rtnetlink (pure Rust) — no `ip` binary dependency.

use std::fs;
use std::net::Ipv4Addr;

use futures::stream::TryStreamExt;
use rtnetlink::new_connection;

/// Guest interface created by libkrun virtio-net.
const IFACE: &str = "eth0";
/// Static guest address (must match gvproxy DHCP/static lease MAC).
const GUEST_IP: Ipv4Addr = Ipv4Addr::new(192, 168, 127, 2);
/// Prefix length for the virtual subnet.
const PREFIX_LEN: u8 = 24;
/// Gateway (= gvproxy) address; also DNS.
const GATEWAY_IP: Ipv4Addr = Ipv4Addr::new(192, 168, 127, 1);

/// Bring up loopback + eth0 with static IP and default route.
///
/// # Errors
///
/// Returns I/O error if eth0 is missing or netlink operations fail.
pub async fn configure_static_eth0() -> std::io::Result<()> {
    let (connection, handle, _) =
        new_connection().map_err(|e| std::io::Error::other(format!("netlink connect: {e}")))?;
    tokio::spawn(connection);

    // lo up
    {
        let mut links = handle.link().get().match_name("lo".to_owned()).execute();
        if let Some(link) = links
            .try_next()
            .await
            .map_err(|e| std::io::Error::other(format!("get lo: {e}")))?
        {
            handle
                .link()
                .set(link.header.index)
                .up()
                .execute()
                .await
                .map_err(|e| std::io::Error::other(format!("lo up: {e}")))?;
        }
    }

    // eth0
    let mut links = handle.link().get().match_name(IFACE.to_owned()).execute();
    let link = links
        .try_next()
        .await
        .map_err(|e| std::io::Error::other(format!("get {IFACE}: {e}")))?
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("{IFACE} not found — virtio-net missing?"),
            )
        })?;
    let idx = link.header.index;

    handle
        .link()
        .set(idx)
        .up()
        .execute()
        .await
        .map_err(|e| std::io::Error::other(format!("{IFACE} up: {e}")))?;

    handle
        .address()
        .add(idx, GUEST_IP.into(), PREFIX_LEN)
        .execute()
        .await
        .or_else(|e| {
            // Already assigned is fine on restart paths.
            if e.to_string().contains("File exists") || e.to_string().contains("EEXIST") {
                Ok(())
            } else {
                Err(std::io::Error::other(format!("addr add: {e}")))
            }
        })?;

    handle
        .route()
        .add()
        .v4()
        .gateway(GATEWAY_IP)
        .execute()
        .await
        .or_else(|e| {
            if e.to_string().contains("File exists") || e.to_string().contains("EEXIST") {
                Ok(())
            } else {
                Err(std::io::Error::other(format!("default route: {e}")))
            }
        })?;

    write_resolv_gateway();
    ensure_hosts_and_hostname();
    Ok(())
}

/// Offline / Disabled network: lo identity only, no eth0 requirement.
pub fn configure_offline() {
    ensure_hosts_and_hostname();
}

/// Point DNS at the gvproxy gateway.
fn write_resolv_gateway() {
    let _ = fs::create_dir_all("/etc");
    let _ = fs::write(
        "/etc/resolv.conf",
        "# Generated by bux-guest (gvproxy gateway DNS)\nnameserver 192.168.127.1\n",
    );
}

/// Ensure `/etc/hosts` and hostname are set for the guest.
fn ensure_hosts_and_hostname() {
    let hosts = std::path::Path::new("/etc/hosts");
    if !hosts.is_file() || fs::read_to_string(hosts).map_or(true, |c| c.is_empty()) {
        let _ = fs::write(
            hosts,
            "127.0.0.1 localhost\n::1 localhost\n192.168.127.2 bux\n",
        );
    }

    let hostname = std::path::Path::new("/etc/hostname");
    if !hostname.is_file() {
        let _ = fs::write(hostname, "bux\n");
    }
    if let Ok(name) = std::ffi::CString::new("bux") {
        unsafe {
            libc::sethostname(name.as_ptr(), 3);
        }
    }
}
